# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('img_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('nickname', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('prefix', models.IntegerField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Resources')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.Resources')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.User')),
            ],
        ),
        migrations.AddField(
            model_name='resources',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.User'),
        ),
    ]
