# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20171124_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resources',
            name='title',
            field=models.CharField(blank=True, default='title1', max_length=250),
            preserve_default=False,
        ),
    ]
