# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20171124_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='img_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='resources',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
