# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20171124_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='resources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cmdb.Resources'),
        ),
    ]
